<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0</TargetFrameworks>
    <AssemblyName>SD.Tools.LinqToSQL3</AssemblyName>
    <RootNamespace>System.Data.Linq</RootNamespace>
    <Version>1.0</Version>
	<LangVersion>11.0</LangVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Authors>Solutions Design bv, LINQPad</Authors>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageLicenseUrl></PackageLicenseUrl>
    <PackageProjectUrl></PackageProjectUrl>
    <PackageTags>Linq to SQL Database Data O/RM ADO.NET</PackageTags>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
    <PackageIconUrl></PackageIconUrl>
    <DocumentationFile></DocumentationFile>
  </PropertyGroup>
	<PropertyGroup Condition="Exists('c:\source.s\LINQPad\LINQPad.snk')">
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>c:\source.s\LINQPad\LINQPad.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>
  <ItemGroup>
    <Compile Remove="obj" />
    <Compile Remove="bin" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <!--We can't use version 6 of Microsoft.Data.SqlClient because it's .NET 8+ only.--> 
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.3" />
  </ItemGroup>	
</Project>