<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net452;net6.0</TargetFrameworks>
    <AssemblyName>SD.Tools.LinqToSQL2</AssemblyName>
    <RootNamespace>System.Data.Linq</RootNamespace>
    <Version>1.0</Version>
	<LangVersion>11.0</LangVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Authors>Solutions Design bv, LINQPad</Authors>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageLicenseUrl></PackageLicenseUrl>
    <PackageProjectUrl></PackageProjectUrl>
    <PackageTags>Linq to SQL Database Data O/RM ADO.NET</PackageTags>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
    <PackageIconUrl></PackageIconUrl>
    <DocumentationFile></DocumentationFile>
  </PropertyGroup>
	<PropertyGroup Condition="Exists('..\..\..\source.s\LINQPad\LINQPad.snk')">
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>..\..\..\source.s\LINQPad\LINQPad.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Security.Permissions">
      <Version>4.6.0</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net452'">
    <Reference Include="System.Transactions" />
    <Reference Include="System.Configuration" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="obj" />
    <Compile Remove="bin" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
    <PackageReference Include="System.Reflection.Emit" Version="4.6.0" />
    <PackageReference Include="System.Reflection.Emit.ILGeneration" Version="4.6.0" />
    <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.6.0" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.1" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.55.0" />
  </ItemGroup>	
</Project>